// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATa9lXeLhGqmv4RZzetEYqetGzH_o0ZAI',
    appId: '1:587867602782:web:08dab2f7ac2727b106d9cf',
    messagingSenderId: '587867602782',
    projectId: 'lole-cargo-app',
    authDomain: 'lole-cargo-app.firebaseapp.com',
    storageBucket: 'lole-cargo-app.appspot.com',
    measurementId: 'G-YQKDK1DL0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGOPa2ewfi22E5VvODgPmBDophCPbdfM',
    appId: '1:587867602782:android:a8350262f02e321f06d9cf',
    messagingSenderId: '587867602782',
    projectId: 'lole-cargo-app',
    storageBucket: 'lole-cargo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSp2KopVPvbYka5tPMYS8hiXfqXhNAUg',
    appId: '1:587867602782:ios:25d30565adb63c9b06d9cf',
    messagingSenderId: '587867602782',
    projectId: 'lole-cargo-app',
    storageBucket: 'lole-cargo-app.appspot.com',
    iosClientId: '587867602782-iii5s27ni7373jvdi82tekf531jt94dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lole',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvSp2KopVPvbYka5tPMYS8hiXfqXhNAUg',
    appId: '1:587867602782:ios:25d30565adb63c9b06d9cf',
    messagingSenderId: '587867602782',
    projectId: 'lole-cargo-app',
    storageBucket: 'lole-cargo-app.appspot.com',
    iosClientId: '587867602782-iii5s27ni7373jvdi82tekf531jt94dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lole',
  );
}
